services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  routing-service:
    build: ./routing-service
    ports:
      - 5000:5000

volumes:
  redis:
    driver: local
